"""create stock_relations table

Revision ID: 8067b4ac40ae
Revises: ea0ff8380505
Create Date: 2026-04-28 12:05:18.941825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8067b4ac40ae'
down_revision: Union[str, None] = 'ea0ff8380505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_stock_id', sa.Integer(), nullable=False),
    sa.Column('to_target', sa.String(length=100), nullable=False),
    sa.Column('to_kind', sa.String(length=20), nullable=False),
    sa.Column('relation_type', sa.String(length=30), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('discovered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_stock_id', 'to_target', 'relation_type', name='uq_relation_triple')
    )
    op.create_index('ix_relations_from', 'stock_relations', ['from_stock_id'], unique=False)
    op.create_index('ix_relations_target', 'stock_relations', ['to_target'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_relations_target', table_name='stock_relations')
    op.drop_index('ix_relations_from', table_name='stock_relations')
    op.drop_table('stock_relations')
    # ### end Alembic commands ###
