"""create macro_factors table

Revision ID: a3f4ec76d96d
Revises: 8067b4ac40ae
Create Date: 2026-04-28 12:05:58.722840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3f4ec76d96d'
down_revision: Union[str, None] = '8067b4ac40ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factor', sa.String(length=40), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('factor', 'date', name='uq_macro_factor_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('macro_factors')
    # ### end Alembic commands ###
