"""add card_data schema_version persona_version to analyses

Revision ID: ea0ff8380505
Revises: f2212d1d1fe4
Create Date: 2026-04-28 11:59:35.410326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea0ff8380505'
down_revision: Union[str, None] = 'f2212d1d1fe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('schema_version', sa.String(length=10), server_default='v1', nullable=False))
    op.add_column('analyses', sa.Column('card_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('analyses', sa.Column('persona_version', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'persona_version')
    op.drop_column('analyses', 'card_data')
    op.drop_column('analyses', 'schema_version')
    # ### end Alembic commands ###
