"""add chat_messages table

Revision ID: f2212d1d1fe4
Revises: e19721f8ce54
Create Date: 2026-04-17 10:27:39.185503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2212d1d1fe4'
down_revision: Union[str, None] = 'e19721f8ce54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_thread_created', 'chat_messages', ['thread_id', 'created_at'], unique=False)
    op.create_index('ix_chat_user_updated', 'chat_messages', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chat_user_updated', table_name='chat_messages')
    op.drop_index('ix_chat_thread_created', table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
